// Generated by CoffeeScript 1.11.1

/*
Multiline comments
 */

(function() {
  var aString, areYouHappy, csOutput, largestNum, largestNumStr, name, smallestNum, smallesttNumStr;

  name = "Phil";

  csOutput = document.getElementById("csoutput");

  csOutput.innerHTML = "Hello " + name + "<br>";

  aString = "I'm a string";

  csOutput.insertAdjacentHTML('beforeend', 'aString is a String<br>')(typeof aString === 'string' ? (largestNum = Number.MAX_VALUE, smallestNum = Number.MIN_VALUE, largestNumStr = "The largest number is " + largestNum + "<br>", smallesttNumStr = "The largest number is " + smallestNum + "<br>", csOutput.insertAdjacentHTML('beforeend', largestNumStr + '<br>'), csOutput.insertAdjacentHTML('beforeend', smallesttNumStr + '<br>'), areYouHappy = false, csOutput.insertAdjacentHTML('beforeend', 'areYouHappy is a Boolean<br>')(typeof areYouHappy === 'boolean' ? csOutput.insertAdjacentHTML('beforeend', "5 + 2 = " + (5 + 2) + "<br>") : void 0)) : void 0);

}).call(this);
